/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateExam: typeof import('./components/CreateExam.vue')['default']
    Exam: typeof import('./components/Exam.vue')['default']
    Registration: typeof import('./components/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignOutDialog: typeof import('./components/SignOutDialog.vue')['default']
  }
}
