services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_FRONTEND_URL=${FRONTEND_URL}
