services:
    builder:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - dist-data:/app/dist

    nginx:
        image: nginx:alpine
        expose:
            - 80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - dist-data:/usr/share/nginx/html
        depends_on:
            - builder

volumes:
    dist-data:
