services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      arguments:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
    expose:
      - 80
